/**
 * Supplier API V1 Types
 * Backend: http://localhost:8080/api/v1/suppliers
 * Authentication: Bearer Token required
 */

// ============================================
// API RESPONSE WRAPPERS
// ============================================

export interface ApiResponse<T> {
  statusCode: number;
  message: string;
  data: T;
  error?: string;
}

export interface PageResponse<T> {
  content: T[];
  pageable: {
    pageNumber: number;
    pageSize: number;
    sort: {
      empty: boolean;
      sorted: boolean;
      unsorted: boolean;
    };
    offset: number;
    paged: boolean;
    unpaged: boolean;
  };
  last: boolean;
  totalElements: number;
  totalPages: number;
  first: boolean;
  size: number;
  number: number;
  sort: {
    empty: boolean;
    sorted: boolean;
    unsorted: boolean;
  };
  numberOfElements: number;
  empty: boolean;
}

// ============================================
// SUPPLIER SUMMARY (GET /api/v1/suppliers) - Basic endpoint
// ============================================

export interface SupplierSummaryResponse {
  supplierId: number;
  supplierCode: string;
  supplierName: string;
  phoneNumber: string;
  email: string;
  status: 'ACTIVE' | 'INACTIVE';
}

// ============================================
// API 6.13: SUPPLIER LIST WITH BUSINESS METRICS
// ============================================

export enum SupplierTier {
  TIER_1 = 'TIER_1',
  TIER_2 = 'TIER_2',
  TIER_3 = 'TIER_3',
}

export interface SupplierListDTO {
  supplierId: number;
  supplierCode: string;
  supplierName: string;
  phoneNumber: string;
  email?: string;
  address?: string;
  tierLevel?: SupplierTier;
  ratingScore?: number;
  totalOrders: number;
  lastOrderDate?: string; // YYYY-MM-DD
  isBlacklisted: boolean;
  isActive: boolean;
  notes?: string;
  createdAt: string; // ISO 8601
  updatedAt?: string; // ISO 8601
  
  // Helper method (calculated on FE)
  isInactive?: () => boolean;
}

export interface SupplierPageResponse {
  suppliers: SupplierListDTO[];
  currentPage: number;
  pageSize: number;
  totalElements: number;
  totalPages: number;
  isFirst: boolean;
  isLast: boolean;
  hasNext: boolean;
  hasPrevious: boolean;
}

// ============================================
// SUPPLIER DETAIL (GET /api/v1/suppliers/{id})
// ============================================

export interface SuppliedItemSummary {
  itemMasterId: number;
  itemCode: string;
  itemName: string;
  categoryName?: string; // Tên danh mục vật tư
  lastImportDate: string | null; // ISO 8601: "2025-11-19T15:30:00" hoặc null
  totalQuantity: number; // Tổng số lượng tồn kho từ tất cả batches
}

export interface SupplierDetailResponse {
  supplierId: number;
  supplierCode: string;
  supplierName: string;
  phoneNumber: string;
  email: string;
  address: string;
  notes: string;
  contactPerson: string;
  isActive: boolean;
  createdAt: string; // ISO 8601
  suppliedItems: SuppliedItemSummary[];
}

// ============================================
// SUPPLIED ITEMS (GET /api/v1/suppliers/{id}/supplied-items)
// ============================================

export interface SuppliedItemResponse {
  itemMasterId: number;
  itemCode: string;
  itemName: string;
  batchId: number;
  lotNumber: string;
  quantitySupplied: number;
  importPrice: number;
  suppliedDate: string; // ISO 8601
  expiryDate?: string; // ISO 8601 (optional for non-cold items)
}

// ============================================
// API 6.14: CREATE SUPPLIER (POST /api/v1/suppliers)
// ============================================

export interface CreateSupplierRequest {
  supplierName: string; // Required, 2-255 chars, unique (case-insensitive)
  phone: string; // Required, 10-11 digits, numeric only (mapped to phoneNumber in service)
  email?: string; // Optional, valid email format, unique if provided
  address?: string; // Optional, max 500 characters
  isBlacklisted?: boolean; // Optional, default false
  notes?: string; // Optional, max 1000 characters
  // Note: supplierCode is auto-generated by BE (SUP-001, SUP-002, ...)
}

// ============================================
// API 6.15: UPDATE SUPPLIER (PUT /api/v1/suppliers/{id})
// ============================================

export interface UpdateSupplierRequest {
  supplierName: string; // Required, 2-255 chars, unique (case-insensitive)
  contactPerson?: string; // Optional, max 255 chars (NEW in V30)
  phoneNumber: string; // Required, 10-11 digits, starts with 0 (Vietnamese format)
  email?: string; // Optional, valid email format, unique if provided
  address?: string; // Optional, max 500 characters
  isActive?: boolean; // Optional, false = Pause orders temporarily
  isBlacklisted?: boolean; // Optional, true = Fraud warning
  notes?: string; // Optional, max 1000 characters
  // Note: Metrics (totalOrders, lastOrderDate) are NOT updated via this API
}

// ============================================
// SUPPLIER RESPONSE (CREATE/UPDATE)
// ============================================

export interface SupplierResponse {
  supplierId: number;
  supplierCode: string; // Auto-generated (SUP-001, SUP-002, ...)
  supplierName: string;
  phoneNumber: string;
  email?: string;
  address?: string;
  contactPerson?: string; // NEW in V30
  isActive: boolean;
  isBlacklisted: boolean; // NEW in V25
  totalOrders: number; // Business metric
  lastOrderDate?: string; // Business metric (YYYY-MM-DD)
  notes?: string;
  status: 'ACTIVE' | 'INACTIVE';
  createdAt: string; // ISO 8601
  updatedAt?: string; // ISO 8601
}

// ============================================
// QUERY PARAMS
// ============================================

export interface SupplierQueryParams {
  page?: number; // Default: 0
  size?: number; // Default: 10
  sort?: string; // Format: "field,direction" (e.g., "supplierName,asc")
  search?: string; // Multi-field search (name, code, phone, email)
}

// ============================================
// API 6.13: SUPPLIER FILTER REQUEST
// ============================================

export interface SupplierFilterRequest {
  page?: number; // Default: 0
  size?: number; // Default: 20, max: 100
  search?: string; // Multi-field search (name, phone, email, code)
  isBlacklisted?: boolean; // Filter by blacklist status (true/false/null)
  isActive?: boolean; // Filter by active status (true/false/null)
  sortBy?: 'supplierName' | 'supplierCode' | 'totalOrders' | 'lastOrderDate' | 'createdAt' | 'tierLevel' | 'ratingScore';
  sortDir?: 'ASC' | 'DESC'; // Default: ASC
}
