-- ============================================
-- DENTAL CLINIC MANAGEMENT SYSTEM - SCHEMA V30
-- Date: 2025-11-29
-- PostgreSQL Database Schema - REFERENCE ONLY
-- ============================================
-- IMPORTANT: This file is for REFERENCE/DOCUMENTATION purposes only
-- Actual database schema is AUTO-GENERATED by Hibernate (ddl-auto: update)
-- DO NOT execute this file manually
--
-- Schema generation flow:
-- 1. dental-clinic-seed-data.sql creates ENUM types (before Hibernate)
-- 2. Hibernate auto-generates all tables from @Entity classes
-- 3. DataInitializer bean loads INSERT statements from seed data
--
-- This file documents the expected schema structure for reference
-- ============================================
-- CHANGES IN V30 (API 6.15 + Issue #23):
--   - API 6.15: PUT /api/v1/warehouse/suppliers/{id} endpoint
--   - Added contact_person column to suppliers table (VARCHAR 255)
--   - Hibernate executes: ALTER TABLE suppliers ADD COLUMN contact_person VARCHAR(255)
--   - Issue #23: Added default value paymentStatus=UNPAID for storage_transactions
--   - Prevents null paymentStatus in DRAFT import transactions
--   - Entity: @Builder.Default private PaymentStatus paymentStatus = PaymentStatus.UNPAID
--   - Update supplier profile: name, contactPerson, phone, email, address, notes
--   - Risk Management: Update isActive (pause orders), isBlacklisted (fraud warning)
--   - Validation: Duplicate name with OTHER suppliers (409), supplier exists (404)
--   - Metrics (totalOrders, lastOrderDate) NOT updated via this API
--   - Log warning when supplier marked as BLACKLISTED
-- CHANGES IN V29 (Architecture Fix - Supplier-Item Auto-Linking):
--   - FIXED: supplier_items table now auto-populated on import
--   - Logic: When import transaction created, auto-create/update SupplierItem record
--   - First import from supplier -> Create new SupplierItem (isPreferred=false, lastPurchaseDate=transactionDate)
--   - Subsequent imports -> Update lastPurchaseDate to latest transactionDate
--   - Impact: GET /inventory/{id}/suppliers now returns actual supplier data
--   - No manual API needed - supplier-item links created organically through import workflow
--   - Repository: Added findBySupplierAndItemMaster() method to SupplierItemRepository
--   - Service: Modified ImportTransactionService.processImportItem() with auto-linking logic
-- CHANGES IN V28 (API 6.14 - Create Supplier):
--   - POST /api/v1/warehouse/suppliers endpoint
--   - Auto-generate supplier_code (SUP-001, SUP-002, ...)
--   - Validate supplier name uniqueness (case-insensitive)
--   - Validate email uniqueness (case-insensitive)
--   - Set defaults: is_active=true, total_orders=0, last_order_date=null
--   - No new columns needed (all fields already exist in suppliers table)
-- CHANGES IN V27 (API 6.13 - Get Suppliers with Metrics):
--   - Added is_blacklisted column to suppliers table (via Entity update)
--   - Hibernate automatically executes: ALTER TABLE suppliers ADD COLUMN is_blacklisted BOOLEAN
--   - Added business metrics: totalOrders, lastOrderDate (already existed)
--   - GET /api/v1/warehouse/suppliers/list endpoint with filters
--   - Auto-update supplier metrics on import transaction
-- CHANGES IN V26 (API 6.12 - Convert Item Quantity):
--   - No schema changes (utility API only)
--   - Added batch conversion endpoint POST /items/units/convert
--   - Supports FLOOR/CEILING/HALF_UP rounding modes
--   - Returns formula for transparency
-- CHANGES IN V25 (Seed Data Initialization Fix):
--   - Added DataInitializer bean for proper seed data loading
--   - Fixed three-phase initialization (ENUMs -> Tables -> Data)
-- CHANGES IN V24 (API 6.11 - Get Item Units):
--   - Added transaction_date column to storage_transactions
--   - Added status column to storage_transactions
--   - VIEW_ITEMS permission granted to INVENTORY_MANAGER
-- CHANGES IN V23 (API 6.7 - Item Masters List):
-- - Added cached_total_quantity, cached_last_import_date, cached_last_updated to item_masters
-- - Purpose: Performance optimization - avoid JOIN/SUM on item_batches for every query
-- ============================================
-- CHANGES IN V22 (API 6.6 - Transaction History):
-- - Added payment_status ENUM (UNPAID, PARTIAL, PAID)
-- - Added transaction_status ENUM (DRAFT, PENDING_APPROVAL, APPROVED, REJECTED, COMPLETED, CANCELLED)
-- - Enhanced storage_transactions table with 8 new fields for payment tracking, approval workflow, appointment linking
-- - Purpose: Track payment status, approval workflow, link export transactions to appointments
-- ============================================
-- CHANGES IN V21:
-- - Added Clinical Rules Engine (service_dependencies table)
-- - Added dependency_rule_type ENUM (REQUIRES_PREREQUISITE, REQUIRES_MIN_DAYS, EXCLUDES_SAME_DAY, BUNDLES_WITH)
-- - Purpose: Enforce clinical workflows, prevent unsafe service combinations
-- ============================================
-- CHANGES IN V20:
-- - Added plan_audit_logs table for treatment plan approval audit trail
-- - Purpose: Track all approval/rejection actions on treatment plans
-- ============================================
-- CHANGES IN V17:
-- - Added service_categories table for grouping services
-- - Added category_id (FK) and display_order to services table
-- - Purpose: Support grouped menu API for frontend booking
-- ============================================

-- ============================================
-- ENUM TYPES (Must be created before tables)
-- ============================================

-- Drop all existing types to ensure clean recreation
DROP TYPE IF EXISTS gender CASCADE;
DROP TYPE IF EXISTS employment_type CASCADE;
DROP TYPE IF EXISTS account_status CASCADE;
DROP TYPE IF EXISTS appointment_status_enum CASCADE;
DROP TYPE IF EXISTS appointment_participant_role_enum CASCADE;
DROP TYPE IF EXISTS shift_status CASCADE;
DROP TYPE IF EXISTS request_status CASCADE;
DROP TYPE IF EXISTS work_shift_category CASCADE;
DROP TYPE IF EXISTS shift_source CASCADE;
DROP TYPE IF EXISTS day_of_week CASCADE;
DROP TYPE IF EXISTS holiday_type CASCADE;
DROP TYPE IF EXISTS time_off_status CASCADE;
DROP TYPE IF EXISTS approval_status CASCADE;
DROP TYPE IF EXISTS appointment_action_type CASCADE;
DROP TYPE IF EXISTS appointment_reason_code CASCADE;
DROP TYPE IF EXISTS dependency_rule_type CASCADE;
DROP TYPE IF EXISTS payment_status CASCADE;
DROP TYPE IF EXISTS transaction_status CASCADE;

CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE employment_type AS ENUM ('FULL_TIME', 'PART_TIME_FIXED', 'PART_TIME_FLEX');
CREATE TYPE account_status AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'LOCKED', 'PENDING_VERIFICATION');
CREATE TYPE appointment_status_enum AS ENUM ('SCHEDULED', 'CHECKED_IN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW');
CREATE TYPE appointment_participant_role_enum AS ENUM ('ASSISTANT', 'SECONDARY_DOCTOR', 'OBSERVER');
CREATE TYPE shift_status AS ENUM ('SCHEDULED', 'ON_LEAVE', 'COMPLETED', 'ABSENT', 'CANCELLED');
CREATE TYPE request_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');
CREATE TYPE work_shift_category AS ENUM ('NORMAL', 'NIGHT');
CREATE TYPE shift_source AS ENUM ('BATCH_JOB', 'REGISTRATION_JOB', 'OT_APPROVAL', 'MANUAL_ENTRY');
CREATE TYPE day_of_week AS ENUM ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY');
CREATE TYPE holiday_type AS ENUM ('NATIONAL', 'COMPANY');
CREATE TYPE time_off_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');
CREATE TYPE approval_status AS ENUM ('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED');
CREATE TYPE appointment_action_type AS ENUM ('CREATE', 'DELAY', 'RESCHEDULE_SOURCE', 'RESCHEDULE_TARGET', 'CANCEL', 'STATUS_CHANGE');
CREATE TYPE appointment_reason_code AS ENUM ('PREVIOUS_CASE_OVERRUN', 'DOCTOR_UNAVAILABLE', 'EQUIPMENT_FAILURE', 'PATIENT_REQUEST', 'OPERATIONAL_REDIRECT', 'OTHER');

-- === V21: Clinical Rules Engine ===
CREATE TYPE dependency_rule_type AS ENUM ('REQUIRES_PREREQUISITE', 'REQUIRES_MIN_DAYS', 'EXCLUDES_SAME_DAY', 'BUNDLES_WITH');

-- === V22: Warehouse Transaction History (API 6.6) ===
CREATE TYPE payment_status AS ENUM ('UNPAID', 'PARTIAL', 'PAID');
CREATE TYPE transaction_status AS ENUM ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED');

-- ============================================
-- CORE TABLES
-- ============================================

-- Base Roles (3 loại: admin, employee, patient)
CREATE TABLE base_roles (
    base_role_id INTEGER PRIMARY KEY,
    base_role_name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Roles (Vai trò cụ thể trong hệ thống)
CREATE TABLE roles (
    role_id VARCHAR(50) PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL UNIQUE,
    base_role_id INTEGER NOT NULL REFERENCES base_roles(base_role_id),
    description TEXT,
    requires_specialization BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Accounts (Tài khoản đăng nhập)
CREATE TABLE accounts (
    account_id SERIAL PRIMARY KEY,
    account_code VARCHAR(20) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id VARCHAR(50) NOT NULL REFERENCES roles(role_id),
    status VARCHAR(50) DEFAULT 'ACTIVE',
    must_change_password BOOLEAN DEFAULT FALSE,
    password_changed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Permissions (Quyền hạn)
CREATE TABLE permissions (
    permission_id VARCHAR(100) PRIMARY KEY,
    permission_name VARCHAR(255) NOT NULL,
    description TEXT,
    resource VARCHAR(100),
    action VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Role Permissions (Quyền của từng vai trò)
CREATE TABLE role_permissions (
    role_id VARCHAR(50) NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
    permission_id VARCHAR(100) NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id)
);

-- Specializations (Chuyên môn nha khoa)
CREATE TABLE specializations (
    specialization_id INTEGER PRIMARY KEY,
    specialization_code VARCHAR(50) UNIQUE NOT NULL,
    specialization_name VARCHAR(255) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Employees (Nhân viên)
CREATE TABLE employees (
    employee_id SERIAL PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
    employee_code VARCHAR(20) UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone VARCHAR(15),
    date_of_birth DATE,
    address TEXT,
    employment_type VARCHAR(50) DEFAULT 'FULL_TIME',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Employee Specializations (Chuyên môn của nhân viên)
CREATE TABLE employee_specializations (
    employee_id INTEGER NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    specialization_id INTEGER NOT NULL REFERENCES specializations(specialization_id) ON DELETE CASCADE,
    PRIMARY KEY (employee_id, specialization_id)
);

-- Patients (Bệnh nhân)
CREATE TABLE patients (
    patient_id SERIAL PRIMARY KEY,
    account_id INTEGER REFERENCES accounts(account_id) ON DELETE SET NULL,
    patient_code VARCHAR(20) UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(15),
    date_of_birth DATE,
    address TEXT,
    gender VARCHAR(10),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Services (Dịch vụ nha khoa)
-- ============================================
-- SERVICE MANAGEMENT TABLES (V17 UPDATE)
-- ============================================

-- Service Categories (V17: Nhóm dịch vụ cho menu FE)
CREATE TABLE service_categories (
    category_id SERIAL PRIMARY KEY,
    category_code VARCHAR(50) UNIQUE NOT NULL,
    category_name VARCHAR(255) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Services (Dịch vụ đơn lẻ - V17: Added category_id, display_order)
CREATE TABLE services (
    service_id SERIAL PRIMARY KEY,
    service_code VARCHAR(50) UNIQUE NOT NULL,
    service_name VARCHAR(255) NOT NULL,
    description TEXT,
    default_duration_minutes INTEGER NOT NULL,
    default_buffer_minutes INTEGER DEFAULT 0,
    price DECIMAL(15,2),
    category_id INTEGER REFERENCES service_categories(category_id) ON DELETE SET NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    specialization_id INTEGER REFERENCES specializations(specialization_id),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_services_category ON services(category_id);
CREATE INDEX idx_services_specialization ON services(specialization_id);

-- === V21: Service Dependencies (Clinical Rules) ===
CREATE TABLE service_dependencies (
    dependency_id SERIAL PRIMARY KEY,
    service_id INTEGER NOT NULL REFERENCES services(service_id) ON DELETE CASCADE,
    dependent_service_id INTEGER NOT NULL REFERENCES services(service_id) ON DELETE CASCADE,
    rule_type dependency_rule_type NOT NULL,
    min_days_apart INTEGER,
    receptionist_note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_min_days_for_rule CHECK (
        (rule_type = 'REQUIRES_MIN_DAYS' AND min_days_apart IS NOT NULL AND min_days_apart > 0) OR
        (rule_type != 'REQUIRES_MIN_DAYS')
    )
);

CREATE INDEX idx_service_deps_service ON service_dependencies(service_id, rule_type);
CREATE INDEX idx_service_deps_dependent ON service_dependencies(dependent_service_id);

-- Rooms (Phòng khám)
CREATE TABLE rooms (
    room_id VARCHAR(50) PRIMARY KEY,
    room_code VARCHAR(50) UNIQUE NOT NULL,
    room_name VARCHAR(255) NOT NULL,
    room_type VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Room Services (Dịch vụ tương thích với phòng)
CREATE TABLE room_services (
    room_id VARCHAR(50) NOT NULL REFERENCES rooms(room_id) ON DELETE CASCADE,
    service_id INTEGER NOT NULL REFERENCES services(service_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (room_id, service_id)
);

-- Work Shifts (Ca làm việc)
CREATE TABLE work_shifts (
    work_shift_id VARCHAR(50) PRIMARY KEY,
    shift_name VARCHAR(100) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    category VARCHAR(50) DEFAULT 'NORMAL',
    is_active BOOLEAN DEFAULT TRUE
);

-- Employee Shifts (Lịch làm việc của nhân viên)
CREATE TABLE employee_shifts (
    employee_shift_id VARCHAR(50) PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    work_date DATE NOT NULL,
    work_shift_id VARCHAR(50) NOT NULL REFERENCES work_shifts(work_shift_id),
    source VARCHAR(50) DEFAULT 'MANUAL_ENTRY',
    is_overtime BOOLEAN DEFAULT FALSE,
    status VARCHAR(50) DEFAULT 'SCHEDULED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (employee_id, work_date, work_shift_id)
);

-- Appointments (Lịch hẹn)
CREATE TABLE appointments (
    appointment_id SERIAL PRIMARY KEY,
    appointment_code VARCHAR(20) UNIQUE NOT NULL,
    patient_id INTEGER NOT NULL REFERENCES patients(patient_id),
    employee_id INTEGER NOT NULL REFERENCES employees(employee_id),
    room_id VARCHAR(50) NOT NULL REFERENCES rooms(room_id),
    appointment_start_time TIMESTAMP NOT NULL,
    appointment_end_time TIMESTAMP NOT NULL,
    expected_duration_minutes INTEGER NOT NULL,
    status VARCHAR(50) DEFAULT 'SCHEDULED',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Appointment Services (Dịch vụ trong lịch hẹn)
CREATE TABLE appointment_services (
    appointment_service_id SERIAL PRIMARY KEY,
    appointment_id INTEGER NOT NULL REFERENCES appointments(appointment_id) ON DELETE CASCADE,
    service_id INTEGER NOT NULL REFERENCES services(service_id),
    service_duration_minutes INTEGER,
    service_buffer_minutes INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Appointment Participants (Phụ tá/Bác sĩ phụ trong lịch hẹn)
CREATE TABLE appointment_participants (
    participant_id SERIAL PRIMARY KEY,
    appointment_id INTEGER NOT NULL REFERENCES appointments(appointment_id) ON DELETE CASCADE,
    employee_id INTEGER NOT NULL REFERENCES employees(employee_id),
    participant_role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (appointment_id, employee_id)
);

-- Appointment Audit Logs (Lịch sử thay đổi lịch hẹn)
CREATE TABLE appointment_audit_logs (
    log_id SERIAL PRIMARY KEY,
    appointment_id INTEGER NOT NULL REFERENCES appointments(appointment_id) ON DELETE CASCADE,
    changed_by_employee_id INTEGER REFERENCES employees(employee_id) ON DELETE SET NULL,
    action_type appointment_action_type NOT NULL,
    reason_code appointment_reason_code,
    old_value TEXT,
    new_value TEXT,
    old_start_time TIMESTAMP,
    new_start_time TIMESTAMP,
    old_status appointment_status_enum,
    new_status appointment_status_enum,
    notes TEXT,
    action_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_appointment ON appointment_audit_logs(appointment_id);
CREATE INDEX idx_audit_action_type ON appointment_audit_logs(action_type);
CREATE INDEX idx_audit_timestamp ON appointment_audit_logs(action_timestamp);

-- ============================================
-- TIME OFF & LEAVE MANAGEMENT
-- ============================================

-- Time Off Types (Loại nghỉ phép)
CREATE TABLE time_off_types (
    type_id VARCHAR(50) PRIMARY KEY,
    type_code VARCHAR(50) UNIQUE NOT NULL,
    type_name VARCHAR(255) NOT NULL,
    is_paid BOOLEAN DEFAULT TRUE,
    requires_approval BOOLEAN DEFAULT TRUE,
    requires_balance BOOLEAN DEFAULT TRUE,
    default_days_per_year DECIMAL(5,2),
    is_active BOOLEAN DEFAULT TRUE
);

-- Employee Leave Balances (Số ngày phép còn lại)
CREATE TABLE employee_leave_balances (
    balance_id SERIAL PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    time_off_type_id VARCHAR(50) NOT NULL REFERENCES time_off_types(type_id),
    year INTEGER NOT NULL,
    total_days DECIMAL(5,2) NOT NULL DEFAULT 0,
    used_days DECIMAL(5,2) NOT NULL DEFAULT 0,
    remaining_days DECIMAL(5,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (employee_id, time_off_type_id, year)
);

-- Time Off Requests (Đơn xin nghỉ phép)
CREATE TABLE time_off_requests (
    request_id VARCHAR(50) PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employees(employee_id),
    time_off_type_id VARCHAR(50) NOT NULL REFERENCES time_off_types(type_id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_days DECIMAL(5,2) NOT NULL,
    reason TEXT,
    status VARCHAR(50) DEFAULT 'PENDING',
    approved_by INTEGER REFERENCES employees(employee_id),
    approved_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- HOLIDAY MANAGEMENT
-- ============================================

-- Holiday Definitions (Định nghĩa ngày lễ)
CREATE TABLE holiday_definitions (
    holiday_id SERIAL PRIMARY KEY,
    holiday_code VARCHAR(50) UNIQUE NOT NULL,
    holiday_name VARCHAR(255) NOT NULL,
    holiday_type VARCHAR(50) NOT NULL,
    month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    day INTEGER NOT NULL CHECK (day BETWEEN 1 AND 31),
    is_recurring BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Holiday Dates (Ngày lễ cụ thể theo năm)
CREATE TABLE holiday_dates (
    holiday_date_id SERIAL PRIMARY KEY,
    holiday_id INTEGER NOT NULL REFERENCES holiday_definitions(holiday_id) ON DELETE CASCADE,
    holiday_date DATE NOT NULL UNIQUE,
    year INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- TREATMENT PLAN AUDIT LOG (V20)
-- ============================================

-- Plan Audit Logs (Lịch sử duyệt Lộ trình điều trị - V20)
CREATE TABLE plan_audit_logs (
    log_id SERIAL PRIMARY KEY,
    plan_id INTEGER NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    performed_by INTEGER NOT NULL,
    notes TEXT,
    old_approval_status approval_status,
    new_approval_status approval_status,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_plan_audit_plan FOREIGN KEY (plan_id)
        REFERENCES patient_treatment_plans(plan_id) ON DELETE CASCADE,
    CONSTRAINT fk_plan_audit_employee FOREIGN KEY (performed_by)
        REFERENCES employees(employee_id) ON DELETE SET NULL
);

CREATE INDEX idx_plan_audit_plan ON plan_audit_logs(plan_id);
CREATE INDEX idx_plan_audit_performed_by ON plan_audit_logs(performed_by);
CREATE INDEX idx_plan_audit_action_type ON plan_audit_logs(action_type);
CREATE INDEX idx_plan_audit_created_at ON plan_audit_logs(created_at);

COMMENT ON TABLE plan_audit_logs IS 'Audit trail for treatment plan approval workflow (V20)';
COMMENT ON COLUMN plan_audit_logs.action_type IS 'Examples: APPROVED, REJECTED, SUBMITTED_FOR_REVIEW';
COMMENT ON COLUMN plan_audit_logs.performed_by IS 'Employee who performed the action';
COMMENT ON COLUMN plan_audit_logs.notes IS 'Reason for rejection or approval notes';

-- ============================================
-- V22: WAREHOUSE TABLES (API 6.6)
-- ============================================

CREATE TABLE storage_transactions (
    storage_transaction_id SERIAL PRIMARY KEY,
    transaction_code VARCHAR(50) UNIQUE NOT NULL,
    type VARCHAR(20) NOT NULL,
    transaction_date TIMESTAMP NOT NULL,
    invoice_number VARCHAR(100),
    total_value DECIMAL(15,2),
    created_by_id INTEGER NOT NULL,
    supplier_id INTEGER,
    description TEXT,
    status VARCHAR(20) DEFAULT 'DRAFT',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    -- V22: Payment tracking fields (for Accountants)
    payment_status payment_status,
    paid_amount DECIMAL(15,2),
    remaining_debt DECIMAL(15,2),
    due_date DATE,

    -- V22: Approval workflow fields (for Managers)
    approval_status transaction_status,
    approved_by_id INTEGER,
    approved_at TIMESTAMP,
    rejected_by_id INTEGER,
    rejected_at TIMESTAMP,
    rejection_reason TEXT,
    cancelled_by_id INTEGER,
    cancelled_at TIMESTAMP,
    cancellation_reason TEXT,

    -- V22: Appointment linking field (for Doctors)
    related_appointment_id INTEGER,

    CONSTRAINT fk_transaction_created_by FOREIGN KEY (created_by_id)
        REFERENCES employees(employee_id) ON DELETE RESTRICT,
    CONSTRAINT fk_transaction_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id) ON DELETE SET NULL,
    CONSTRAINT fk_transaction_approved_by FOREIGN KEY (approved_by_id)
        REFERENCES employees(employee_id) ON DELETE SET NULL,
    CONSTRAINT fk_transaction_rejected_by FOREIGN KEY (rejected_by_id)
        REFERENCES employees(employee_id) ON DELETE SET NULL,
    CONSTRAINT fk_transaction_cancelled_by FOREIGN KEY (cancelled_by_id)
        REFERENCES employees(employee_id) ON DELETE SET NULL,
    CONSTRAINT fk_transaction_appointment FOREIGN KEY (related_appointment_id)
        REFERENCES appointments(appointment_id) ON DELETE SET NULL
);

CREATE INDEX idx_storage_transactions_code ON storage_transactions(transaction_code);
CREATE INDEX idx_storage_transactions_type ON storage_transactions(type);
CREATE INDEX idx_storage_transactions_created_by ON storage_transactions(created_by_id);
CREATE INDEX idx_storage_transactions_supplier ON storage_transactions(supplier_id);
CREATE INDEX idx_storage_transactions_payment_status ON storage_transactions(payment_status);
CREATE INDEX idx_storage_transactions_approval_status ON storage_transactions(approval_status);
CREATE INDEX idx_storage_transactions_appointment ON storage_transactions(related_appointment_id);
CREATE INDEX idx_storage_transactions_created_at ON storage_transactions(created_at);

COMMENT ON TABLE storage_transactions IS 'Warehouse transactions with payment tracking, approval workflow, and appointment linking (V22/API 6.6)';
COMMENT ON COLUMN storage_transactions.payment_status IS 'Payment status for IMPORT transactions: UNPAID, PARTIAL, PAID';
COMMENT ON COLUMN storage_transactions.approval_status IS 'Approval workflow status: DRAFT, PENDING_APPROVAL, APPROVED, REJECTED, COMPLETED, CANCELLED';
COMMENT ON COLUMN storage_transactions.related_appointment_id IS 'Links EXPORT transactions to patient appointments for clinical context';

-- Item Categories (Danh mục vật tư)
CREATE TABLE item_categories (
    category_id SERIAL PRIMARY KEY,
    category_code VARCHAR(50) UNIQUE NOT NULL,
    category_name VARCHAR(255) NOT NULL,
    description TEXT,
    parent_category_id INTEGER,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_item_category_parent FOREIGN KEY (parent_category_id)
        REFERENCES item_categories(category_id) ON DELETE SET NULL
);

CREATE INDEX idx_item_categories_code ON item_categories(category_code);
CREATE INDEX idx_item_categories_parent ON item_categories(parent_category_id);

COMMENT ON TABLE item_categories IS 'Item categories for warehouse management';

-- Item Masters (Định nghĩa vật tư - API 6.9)
CREATE TABLE item_masters (
    item_master_id SERIAL PRIMARY KEY,
    item_code VARCHAR(50) UNIQUE NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    description TEXT,
    category_id INTEGER,
    warehouse_type VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    unit_of_measure VARCHAR(50),
    min_stock_level INTEGER NOT NULL DEFAULT 0,
    max_stock_level INTEGER NOT NULL DEFAULT 0,
    current_market_price DECIMAL(15,2) DEFAULT 0,
    is_prescription_required BOOLEAN NOT NULL DEFAULT FALSE,
    default_shelf_life_days INTEGER,
    is_active BOOLEAN DEFAULT TRUE,
    cached_total_quantity INTEGER DEFAULT 0,
    cached_last_import_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_item_master_category FOREIGN KEY (category_id)
        REFERENCES item_categories(category_id) ON DELETE SET NULL,
    CONSTRAINT chk_stock_levels CHECK (min_stock_level < max_stock_level),
    CONSTRAINT chk_shelf_life CHECK (default_shelf_life_days IS NULL OR default_shelf_life_days BETWEEN 1 AND 3650)
);

CREATE INDEX idx_item_masters_code ON item_masters(item_code);
CREATE INDEX idx_item_masters_name ON item_masters(item_name);
CREATE INDEX idx_item_masters_category ON item_masters(category_id);
CREATE INDEX idx_item_masters_warehouse_type ON item_masters(warehouse_type);
CREATE INDEX idx_item_masters_cached_quantity ON item_masters(cached_total_quantity);

COMMENT ON TABLE item_masters IS 'Item master data with unit hierarchy support (API 6.9)';
COMMENT ON COLUMN item_masters.is_prescription_required IS 'Healthcare compliance: TRUE for prescription-required medications';
COMMENT ON COLUMN item_masters.default_shelf_life_days IS 'Default shelf life in days (1-3650), NULL for non-perishable items';
COMMENT ON COLUMN item_masters.cached_total_quantity IS 'Denormalized total stock quantity for performance';

-- Item Units (Đơn vị đo lường vật tư - API 6.9)
CREATE TABLE item_units (
    unit_id SERIAL PRIMARY KEY,
    item_master_id INTEGER NOT NULL,
    unit_name VARCHAR(50) NOT NULL,
    conversion_rate INTEGER NOT NULL,
    is_base_unit BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER,
    is_default_import_unit BOOLEAN NOT NULL DEFAULT FALSE,
    is_default_export_unit BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_item_unit_master FOREIGN KEY (item_master_id)
        REFERENCES item_masters(item_master_id) ON DELETE CASCADE,
    CONSTRAINT chk_conversion_rate CHECK (conversion_rate >= 1),
    CONSTRAINT uq_item_unit_name UNIQUE (item_master_id, unit_name)
);

CREATE INDEX idx_item_units_item_master ON item_units(item_master_id);
CREATE INDEX idx_item_units_base_unit ON item_units(is_base_unit);
CREATE INDEX idx_item_units_active ON item_units(is_active);

COMMENT ON TABLE item_units IS 'Unit hierarchy for items (e.g., Box -> Strip -> Pill) - API 6.9, 6.10';
COMMENT ON COLUMN item_units.conversion_rate IS 'Conversion rate to base unit (base unit = 1)';
COMMENT ON COLUMN item_units.is_active IS 'Soft delete flag: false = deprecated unit, hide from dropdown but keep in history';
COMMENT ON COLUMN item_units.is_default_import_unit IS 'UX optimization: default unit for import transactions';
COMMENT ON COLUMN item_units.is_default_export_unit IS 'UX optimization: default unit for export transactions';

-- ============================================
-- WAREHOUSE AUDIT LOGS
-- ============================================
CREATE TABLE warehouse_audit_logs (
    log_id SERIAL PRIMARY KEY,
    transaction_id INTEGER,
    action_type VARCHAR(50) NOT NULL,
    performed_by INTEGER,
    action_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    old_values JSONB,
    new_values JSONB,
    notes TEXT,

    CONSTRAINT fk_audit_transaction FOREIGN KEY (transaction_id)
        REFERENCES storage_transactions(transaction_id) ON DELETE CASCADE,
    CONSTRAINT fk_audit_performer FOREIGN KEY (performed_by)
        REFERENCES employees(employee_id) ON DELETE SET NULL
);

CREATE INDEX idx_audit_logs_transaction ON warehouse_audit_logs(transaction_id);
CREATE INDEX idx_audit_logs_timestamp ON warehouse_audit_logs(action_timestamp);

-- ============================================
-- SUPPLIERS (Nhà cung cấp)
-- ============================================
CREATE TABLE suppliers (
    supplier_id SERIAL PRIMARY KEY,
    supplier_code VARCHAR(50) NOT NULL UNIQUE,
    supplier_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    email VARCHAR(100),
    address TEXT,

    -- Business Metrics (API 6.13)
    tier_level VARCHAR(20) NOT NULL DEFAULT 'TIER_3',
    rating_score DECIMAL(3,1) DEFAULT 0.0,
    total_orders INTEGER DEFAULT 0,
    last_order_date DATE,
    is_blacklisted BOOLEAN NOT NULL DEFAULT FALSE,

    notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_suppliers_code ON suppliers(supplier_code);
CREATE INDEX idx_suppliers_name ON suppliers(supplier_name);
CREATE INDEX idx_suppliers_active ON suppliers(is_active);
CREATE INDEX idx_suppliers_blacklisted ON suppliers(is_blacklisted);

COMMENT ON TABLE suppliers IS 'Nhà cung cấp vật tư nha khoa';
COMMENT ON COLUMN suppliers.tier_level IS 'Phân loại ưu tiên: TIER_1 (cao nhất), TIER_2 (ổn định), TIER_3 (dự phòng)';
COMMENT ON COLUMN suppliers.rating_score IS 'Điểm đánh giá chất lượng (0.0 - 5.0)';
COMMENT ON COLUMN suppliers.total_orders IS 'Tổng số đơn hàng đã nhập từ NCC này - dùng để đánh giá độ tin cậy';
COMMENT ON COLUMN suppliers.last_order_date IS 'Ngày nhập hàng gần nhất - tracking hoạt động của NCC';
COMMENT ON COLUMN suppliers.is_blacklisted IS 'Cờ đánh dấu NCC bị đưa vào danh sách đen (quality/fraud issues)';

-- ============================================
-- SUPPLIER ITEMS (Many-to-Many)
-- ============================================
CREATE TABLE supplier_items (
    supplier_item_id SERIAL PRIMARY KEY,
    supplier_id INTEGER NOT NULL,
    item_master_id INTEGER NOT NULL,
    supplier_item_code VARCHAR(100),
    lead_time_days INTEGER DEFAULT 7,
    min_order_quantity INTEGER DEFAULT 1,
    is_preferred BOOLEAN DEFAULT FALSE,
    last_purchase_price DECIMAL(15,2),
    last_purchase_date DATE,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_supplier_item_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id) ON DELETE CASCADE,
    CONSTRAINT fk_supplier_item_master FOREIGN KEY (item_master_id)
        REFERENCES item_masters(item_master_id) ON DELETE CASCADE,
    CONSTRAINT uq_supplier_item UNIQUE (supplier_id, item_master_id)
);

CREATE INDEX idx_supplier_items_supplier ON supplier_items(supplier_id);
CREATE INDEX idx_supplier_items_item ON supplier_items(item_master_id);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX idx_employees_account ON employees(account_id);
CREATE INDEX idx_employees_code ON employees(employee_code);
CREATE INDEX idx_patients_code ON patients(patient_code);
CREATE INDEX idx_appointments_patient ON appointments(patient_id);
CREATE INDEX idx_appointments_employee ON appointments(employee_id);
CREATE INDEX idx_appointments_room ON appointments(room_id);
CREATE INDEX idx_appointments_start_time ON appointments(appointment_start_time);
CREATE INDEX idx_appointment_services_appointment ON appointment_services(appointment_id);
CREATE INDEX idx_appointment_participants_appointment ON appointment_participants(appointment_id);
CREATE INDEX idx_employee_shifts_employee ON employee_shifts(employee_id);
CREATE INDEX idx_employee_shifts_date ON employee_shifts(work_date);
CREATE INDEX idx_time_off_requests_employee ON time_off_requests(employee_id);
CREATE INDEX idx_time_off_requests_status ON time_off_requests(status);

-- ============================================
-- END OF SCHEMA V23 (Updated with warehouse tables)
-- ============================================
