package com.dental.clinic.management.working_schedule.mapper;

import org.springframework.stereotype.Component;

import com.dental.clinic.management.working_schedule.domain.WorkShift;
import com.dental.clinic.management.working_schedule.dto.request.CreateWorkShiftRequest;
import com.dental.clinic.management.working_schedule.dto.request.UpdateWorkShiftRequest;
import com.dental.clinic.management.working_schedule.dto.response.WorkShiftResponse;

/**
 * Mapper for converting between WorkShift entity and DTOs.
 */
@Component
public class WorkShiftMapper {

    /**
     * Convert CreateWorkShiftRequest to WorkShift entity.
     * Note: workShiftId and category will be set by the service layer.
     */
    public WorkShift toEntity(CreateWorkShiftRequest request) {
        WorkShift workShift = new WorkShift();
        // workShiftId will be set by service after generation
        workShift.setShiftName(request.getShiftName());
        workShift.setStartTime(request.getStartTime());
        workShift.setEndTime(request.getEndTime());
        // Category will be auto-generated by service based on time range
        workShift.setIsActive(true);
        return workShift;
    }

    /**
     * Update entity from UpdateWorkShiftRequest.
     * Only updates non-null fields.
     * Note: Category is auto-updated by service when time changes.
     */
    public void updateEntity(WorkShift workShift, UpdateWorkShiftRequest request) {
        if (request.getShiftName() != null) {
            workShift.setShiftName(request.getShiftName());
        }
        if (request.getStartTime() != null) {
            workShift.setStartTime(request.getStartTime());
        }
        if (request.getEndTime() != null) {
            workShift.setEndTime(request.getEndTime());
        }
        // Category is auto-updated by service based on time changes
    }

    /**
     * Convert WorkShift entity to WorkShiftResponse.
     * Includes calculated durationHours.
     */
    public WorkShiftResponse toResponse(WorkShift workShift) {
        return WorkShiftResponse.builder()
                .workShiftId(workShift.getWorkShiftId())
                .shiftName(workShift.getShiftName())
                .startTime(workShift.getStartTime())
                .endTime(workShift.getEndTime())
                .category(workShift.getCategory())
                .isActive(workShift.getIsActive())
                .durationHours(workShift.getDurationHours())
                .build();
    }
}
